#!/bin/bash

# adjust path if neccessary, add arguments here for host/port/user/password/retain/tls
PUB_CMD="/usr/bin/mosquitto_pub"

# adjust path if neccessary, add --server argument if you want to use specific speedtest server
OUTPUT=$(/usr/bin/speedtest-cli --simple)

TS=`/bin/date +%s`000

while read -r line ; do
    PARAMS=$(echo "$line $TS"  | sed -n 's/\([a-zA-Z]*\): \([0-9.]*\) \(.*\) \(.*\)/-t "speedtest/status/\1" -m "{\\"val\\":\2,\\"unit\\":\\"\3\\",\\"ts\\":\4}"/p')
    if [ ! -z "$PARAMS" ]; then
        $($PUB_CMD $PARAMS)
    fi
done <<< "$OUTPUT"
